export const products = [
  {
    id: 1,
    name: { newArrival: "New Arrival 1", topRated: "Top Rated 1" },
    image: "img/new-product-img/new-product-1.jpg",
    price: 29.99,
  },
  {
    id: 2,
    name: { newArrival: "New Arrival 2", topRated: "Top Rated 2" },
    image: "img/new-product-img/new-product-2.jpg",
    price: 34.99,
    discount: "15% off",
  },
  {
    id: 3,
    name: { newArrival: "New Arrival 3", topRated: "Top Rated 3" },
    image: "img/new-product-img/new-product-3.jpg",
    price: 39.99,
    discount: "10% off",
  },
  {
    id: 4,
    name: { newArrival: "New Arrival 4", topRated: "Top Rated 4" },
    image: "img/new-product-img/new-product-4.jpg",
    price: 24.99,
  },
  {
    id: 5,
    name: { newArrival: "New Arrival 5", topRated: "Top Rated 5" },
    image: "img/new-product-img/new-product-5.jpg",
    price: 19.99,
  },
  {
    id: 6,
    name: { newArrival: "New Arrival 6", topRated: "Top Rated 6" },
    image: "img/new-product-img/new-product-6.jpg",
    price: 49.99,
    discount: "5% off",
  },
  {
    id: 7,
    name: { newArrival: "New Arrival 7", topRated: "Top Rated 7" },
    image: "img/new-product-img/new-product-7.jpg",
    price: 44.99,
  },
  {
    id: 8,
    name: { newArrival: "New Arrival 8", topRated: "Top Rated 8" },
    image: "img/new-product-img/new-product-8.jpg",
    price: 54.99,
  },
  {
    id: 9,
    name: { newArrival: "New Arrival 9", topRated: "Top Rated 9" },
    image: "img/new-product-img/new-product-9.jpg",
    price: 39.99,
    discount: "20% off",
  },
  {
    id: 10,
    name: { newArrival: "New Arrival 10", topRated: "Top Rated 10" },
    image: "img/new-product-img/new-product-10.jpg",
    price: 59.99,
  },
  {
    id: 11,
    name: { newArrival: "New Arrival 11", topRated: "Top Rated 11" },
    image: "img/new-product-img/new-product-7.jpg",
    price: 29.99,
  },
  {
    id: 12,
    name: { newArrival: "New Arrival 12", topRated: "Top Rated 12" },
    image: "img/new-product-img/new-product-8.jpg",
    price: 34.99,
  },
  {
    id: 13,
    name: { newArrival: "New Arrival 13", topRated: "Top Rated 13" },
    image: "img/new-product-img/new-product-10.jpg",
    price: 39.99,
    discount: "15% off",
  },
  {
    id: 14,
    name: { newArrival: "New Arrival 14", topRated: "Top Rated 14" },
    image: "img/new-product-img/new-product-1.jpg",
    price: 24.99,
  },
];
